build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.22
  amd64: ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.22
  armv7: ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.22
labels:
  org.opencontainers.image.title: "Sungrow Edge Daemon"
  org.opencontainers.image.description: "Poll Sungrow inverter and upload telemetry to VPS"
  org.opencontainers.image.source: "https://github.com/Wim/SolarEdge-to-VPS"
